require("plugins")
require("plugins.lsp")
require("plugins.mason")
require("plugins.cmp")
require("plugins.formatter")
require("plugins.git-signs")
require("plugins.nvim-ts")
require("plugins.nvim-tree")

require("configs")
require("keymaps")
